export interface StoicQuote {
  quote: string;
  author: string;
}

export const STOIC_QUOTES: StoicQuote[] = [
  { quote: "You have power over your mind, not outside events.", author: "Marcus Aurelius" },
  { quote: "The happiness of your life depends upon the quality of your thoughts.", author: "Marcus Aurelius" },
  { quote: "Waste no more time arguing what a good man should be. Be one.", author: "Marcus Aurelius" },
  { quote: "If it is not right, do not do it; if it is not true, do not say it.", author: "Marcus Aurelius" },
  { quote: "Very little is needed to make a happy life.", author: "Marcus Aurelius" },
  { quote: "The best revenge is not to be like your enemy.", author: "Marcus Aurelius" },
  { quote: "Confine yourself to the present.", author: "Marcus Aurelius" },
  { quote: "Objective judgment, now, at this very moment.", author: "Marcus Aurelius" },
  { quote: "Dwell on the beauty of life. Watch the stars, and see yourself running with them.", author: "Marcus Aurelius" },
  { quote: "The impediment to action advances action. What stands in the way becomes the way.", author: "Marcus Aurelius" },
  { quote: "When you arise in the morning, think of what a privilege it is to be alive.", author: "Marcus Aurelius" },
  { quote: "Look well into yourself; there is a source of strength which will always spring up.", author: "Marcus Aurelius" },
  { quote: "Our life is what our thoughts make it.", author: "Marcus Aurelius" },
  { quote: "Do every act of your life as if it were your last.", author: "Marcus Aurelius" },
  { quote: "You can also commit injustice by doing nothing.", author: "Marcus Aurelius" },
  { quote: "Accept the things to which fate binds you.", author: "Marcus Aurelius" },
  { quote: "The soul becomes dyed with the color of its thoughts.", author: "Marcus Aurelius" },
  { quote: "Do not be overheard complaining, not even to yourself.", author: "Marcus Aurelius" },
  { quote: "No one can lose either the past or the future.", author: "Marcus Aurelius" },
  { quote: "To bear this worthily is good fortune.", author: "Marcus Aurelius" },
  { quote: "If someone can prove me wrong, I will gladly change.", author: "Marcus Aurelius" },
  { quote: "All that you see will soon perish.", author: "Marcus Aurelius" },
  { quote: "The present is all we ever have.", author: "Marcus Aurelius" },
  { quote: "Do not act as if you had ten thousand years to throw away.", author: "Marcus Aurelius" },
  { quote: "Nothing happens to anyone that he cannot endure.", author: "Marcus Aurelius" },
  { quote: "Fire feeds on obstacles.", author: "Marcus Aurelius" },
  { quote: "The greater part of progress is the desire to progress.", author: "Seneca" },
  { quote: "Luck is what happens when preparation meets opportunity.", author: "Seneca" },
  { quote: "We suffer more often in imagination than in reality.", author: "Seneca" },
  { quote: "Difficulties strengthen the mind, as labor does the body.", author: "Seneca" },
  { quote: "No man is more unhappy than he who never faces adversity.", author: "Seneca" },
  { quote: "If a man knows not to which port he sails, no wind is favorable.", author: "Seneca" },
  { quote: "It is not that we have a short time to live, but that we waste a lot of it.", author: "Seneca" },
  { quote: "Begin at once to live, and count each separate day as a separate life.", author: "Seneca" },
  { quote: "He who is brave is free.", author: "Seneca" },
  { quote: "Every new beginning comes from some other beginning's end.", author: "Seneca" },
  { quote: "Associate with those who will make a better man of you.", author: "Seneca" },
  { quote: "A gem cannot be polished without friction.", author: "Seneca" },
  { quote: "Sometimes even to live is an act of courage.", author: "Seneca" },
  { quote: "As long as you live, keep learning how to live.", author: "Seneca" },
  { quote: "True happiness is to enjoy the present without anxious dependence upon the future.", author: "Seneca" },
  { quote: "No one can have a peaceful life who thinks too much about lengthening it.", author: "Seneca" },
  { quote: "Wherever there is a human being, there is an opportunity for kindness.", author: "Seneca" },
  { quote: "He who fears death will never do anything worthy of a living man.", author: "Seneca" },
  { quote: "Throw me to the wolves and I will return leading the pack.", author: "Seneca" },
  { quote: "The whole future lies in uncertainty: live immediately.", author: "Seneca" },
  { quote: "No man was ever wise by chance.", author: "Seneca" },
  { quote: "One of the most beautiful qualities of true friendship is to understand and be understood.", author: "Seneca" },
  { quote: "A gift consists not in what is done, but in the spirit in which it is done.", author: "Seneca" },
  { quote: "Most powerful is he who has himself in his own power.", author: "Seneca" },
  { quote: "Life is long if you know how to use it.", author: "Seneca" },
  { quote: "The wise man is content with his lot, whatever it may be.", author: "Seneca" },
  { quote: "No easy path leads from the earth to the stars.", author: "Seneca" },
  { quote: "How does it help to make troubles heavier by bemoaning them?", author: "Seneca" },
  { quote: "First learn the meaning of what you say, and then speak.", author: "Epictetus" },
  { quote: "It is not what happens to you, but how you react to it that matters.", author: "Epictetus" },
  { quote: "Make the best use of what is in your power, and take the rest as it happens.", author: "Epictetus" },
  { quote: "No man is free who is not master of himself.", author: "Epictetus" },
  { quote: "Wealth consists not in having great possessions, but in having few wants.", author: "Epictetus" },
  { quote: "If you want to improve, be content to be thought foolish and stupid.", author: "Epictetus" },
  { quote: "Do not seek for events to happen as you wish, but wish them to happen as they do happen.", author: "Epictetus" },
  { quote: "Only the educated are free.", author: "Epictetus" },
  { quote: "Nature gave us one tongue and two ears so we could hear twice as much as we speak.", author: "Epictetus" },
  { quote: "Freedom is the only worthy goal in life.", author: "Epictetus" },
  { quote: "No great thing is created suddenly.", author: "Epictetus" },
  { quote: "Know first who you are, and then adorn yourself accordingly.", author: "Epictetus" },
  { quote: "If you wish to be a writer, write.", author: "Epictetus" },
  { quote: "Man is disturbed not by things, but by the views he takes of them.", author: "Epictetus" },
  { quote: "Difficulty shows what men are.", author: "Epictetus" },
  { quote: "Whoever then wishes to be free, let him neither wish for anything nor avoid anything that depends on others.", author: "Epictetus" },
  { quote: "Take away your opinion, and then there is taken away the complaint.", author: "Epictetus" },
  { quote: "Attach yourself to what is spiritually superior.", author: "Epictetus" },
  { quote: "If anyone tells you someone has spoken ill of you, do not make excuses.", author: "Epictetus" },
  { quote: "Don't explain your philosophy. Embody it.", author: "Epictetus" },
  { quote: "He is a wise man who does not grieve for the things he has not.", author: "Epictetus" },
  { quote: "We have two ears and one mouth so that we can listen twice as much as we speak.", author: "Epictetus" },
  { quote: "Practice yourself, for heaven's sake, in little things.", author: "Epictetus" },
  { quote: "To accuse others for one's own misfortunes is a sign of want of education.", author: "Epictetus" },
  { quote: "Demand not that things happen as you wish, but wish them to happen as they do.", author: "Epictetus" },
  { quote: "Silence is safer than speech.", author: "Epictetus" },
  { quote: "Reason can shape itself to any purpose.", author: "Epictetus" },
  { quote: "A man should so live that his happiness shall depend as little as possible on external things.", author: "Epictetus" },
  { quote: "If you seek truth, you will not seek victory by dishonorable means.", author: "Epictetus" },
  { quote: "The end may be noble, but the means must be fitting.", author: "Musonius Rufus" },
  { quote: "No one can live well unless he has learned to despise pleasure.", author: "Musonius Rufus" },
  { quote: "People are born for one another.", author: "Marcus Aurelius" },
  { quote: "What is not good for the hive is not good for the bee.", author: "Marcus Aurelius" },
  { quote: "External things are not the problem. It is your assessment of them.", author: "Marcus Aurelius" },
  { quote: "The cucumber is bitter? Then throw it out.", author: "Marcus Aurelius" },
  { quote: "Do what nature demands. Get a move on.", author: "Marcus Aurelius" },
  { quote: "When jarred, unavoidably, by circumstances, revert at once to yourself.", author: "Marcus Aurelius" },
  { quote: "Your ability to control your thoughts is your true power.", author: "Marcus Aurelius" },
  { quote: "How much more harmful are the consequences of anger than the causes of it.", author: "Marcus Aurelius" },
  { quote: "A person should not be too busy to think about life.", author: "Marcus Aurelius" },
  { quote: "The universe is change; our life is what our thoughts make it.", author: "Marcus Aurelius" },
  { quote: "He who lives in harmony with himself lives in harmony with the universe.", author: "Marcus Aurelius" },
  { quote: "All is ephemeral: both memory and the object of memory.", author: "Marcus Aurelius" },
  { quote: "To live happily is an inward power of the soul.", author: "Marcus Aurelius" },
  { quote: "The mind that is anxious about future events is miserable.", author: "Seneca" },
  { quote: "Calamity is virtue's opportunity.", author: "Seneca" },
  { quote: "No person has the power to have everything they want.", author: "Seneca" },
  { quote: "A setback has often cleared the way for greater prosperity.", author: "Seneca" },
  { quote: "It is quality rather than quantity that matters.", author: "Seneca" },
  { quote: "Leisure without study is death.", author: "Seneca" },
  { quote: "The wise man regards everything as his own that belongs to all.", author: "Seneca" },
  { quote: "Start at once and regard each day as a separate life.", author: "Seneca" },
  { quote: "No one is free who is a slave to the body.", author: "Seneca" },
  { quote: "If you are pained by any external thing, it is not this thing that disturbs you.", author: "Marcus Aurelius" },
  { quote: "To refrain from imitation is the best revenge.", author: "Marcus Aurelius" },
  { quote: "Do not hope that events will turn out the way you want; welcome events in whichever way they happen.", author: "Epictetus" },
  { quote: "Those who are free of resentful thoughts surely find peace.", author: "Marcus Aurelius" },
  { quote: "The willing are led by fate, the reluctant are dragged.", author: "Cleanthes" },
  { quote: "No evil is honorable; but death is honorable; therefore death is not evil.", author: "Zeno of Citium" },
  { quote: "Man conquers the world by conquering himself.", author: "Zeno of Citium" },
  { quote: "Well-being is attained by little and little, and nevertheless is no little thing itself.", author: "Zeno of Citium" },
  { quote: "Better to trip with the feet than with the tongue.", author: "Zeno of Citium" },
  { quote: "The goal of life is living in agreement with nature.", author: "Zeno of Citium" },
];
